// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface AccordionStoryblok {
  title: string;
  displayTitleAsHeading?: boolean;
  headingLevel?: string;
  content: RichtextStoryblok;
  variant: "subtle" | "callout";
  component: "accordion";
  _uid: string;
  [k: string]: any;
}

export interface AccordionGroupStoryblok {
  accordions: AccordionStoryblok[];
  component: "accordionGroup";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface ActionBannerStoryblok {
  heading: string;
  body?: RichtextStoryblok;
  cta: ButtonLinkStoryblok[];
  image: AssetStoryblok;
  variant?: "fullWidth" | "fullWidthSubtle";
  component: "actionBanner";
  _uid: string;
  [k: string]: any;
}

export interface ActionBannerDefaultStoryblok {
  heading: string;
  body?: RichtextStoryblok;
  cta: ButtonLinkStoryblok[];
  variant?: "default" | "subtle";
  component: "actionBannerDefault";
  _uid: string;
  [k: string]: any;
}

export interface AuthorStoryblok {
  name: string;
  jobTitle?: string;
  image?: AssetStoryblok;
  component: "author";
  _uid: string;
  [k: string]: any;
}

export interface BlogPostStoryblok {
  title: string;
  image: AssetStoryblok;
  date: string;
  introText: string;
  content: RichtextStoryblok;
  author: (ISbStoryData<AuthorStoryblok> | string)[];
  metadata?: MetadataStoryblok[];
  excludeFromHomepage?: boolean;
  component: "blogPost";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface ButtonLinkStoryblok {
  text: string;
  link: MultilinkStoryblok;
  variant: "" | "cta" | "primary" | "secondary" | "inverse";
  component: "buttonLink";
  _uid: string;
  [k: string]: any;
}

export interface CardStoryblok {
  heading: string;
  body: string;
  link?: MultilinkStoryblok;
  component: "card";
  _uid: string;
  [k: string]: any;
}

export interface CardContentStoryblok {
  title?: string;
  body?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  image?: AssetStoryblok;
  component: "cardContent";
  _uid: string;
  [k: string]: any;
}

export interface CardGridStoryblok {
  cards: CardStoryblok[];
  component: "cardGrid";
  _uid: string;
  [k: string]: any;
}

export interface CategoryLandingPageStoryblok {
  header?: (HeroStoryblok | PageHeaderStoryblok)[];
  metadata?: MetadataStoryblok[];
  content?: (ActionBannerStoryblok | GridSectionStoryblok | ActionBannerDefaultStoryblok)[];
  component: "categoryLandingPage";
  _uid: string;
  [k: string]: any;
}

export interface CategoryNavigationStoryblok {
  pageHeader: PageHeaderStoryblok[];
  cardGrid: CardGridStoryblok[];
  metadata?: MetadataStoryblok[];
  component: "categoryNavigation";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | AccordionStoryblok
    | AccordionGroupStoryblok
    | ActionBannerStoryblok
    | ActionBannerDefaultStoryblok
    | AuthorStoryblok
    | BlogPostStoryblok
    | ButtonLinkStoryblok
    | CardStoryblok
    | CardContentStoryblok
    | CardGridStoryblok
    | CategoryLandingPageStoryblok
    | CategoryNavigationStoryblok
    | GridStoryblok
    | GridItemStoryblok
    | GridSectionStoryblok
    | GridSectionItemStoryblok
    | HeroStoryblok
    | HomepageStoryblok
    | HomepageHeroStoryblok
    | IframeStoryblok
    | ImageOrVideoStoryblok
    | InDepthArticleStoryblok
    | InfoPageStoryblok
    | ListItemStoryblok
    | MarkdownStoryblok
    | MetadataStoryblok
    | NestedRichTextStoryblok
    | NestedTableStoryblok
    | NewsArticleStoryblok
    | OrderedListStoryblok
    | PageStoryblok
    | PageHeaderStoryblok
    | PodcastStoryblok
    | PromoBoxStoryblok
    | QuoteStoryblok
    | RelatedLinkStoryblok
    | RelatedNewsLinkStoryblok
    | SpotlightStoryblok
    | YoutubeEmbedStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface GridItemStoryblok {
  cols?: string;
  block?: CardStoryblok[];
  component: "gridItem";
  _uid: string;
  [k: string]: any;
}

export interface GridSectionStoryblok {
  heading?: string;
  lead?: RichtextStoryblok;
  showHeading?: boolean;
  theme: "subtle" | "impact" | "transparent";
  verticalPadding?: "small" | "medium" | "large";
  content?: GridSectionItemStoryblok[];
  component: "gridSection";
  _uid: string;
  [k: string]: any;
}

export interface GridSectionItemStoryblok {
  columns?: "12" | "6" | "4";
  cards?: CardStoryblok[];
  component: "gridSectionItem";
  _uid: string;
  [k: string]: any;
}

export interface HeroStoryblok {
  title: string;
  summary?: string;
  description?: string;
  image: AssetStoryblok;
  cta?: ButtonLinkStoryblok[];
  theme?: "subtle" | "impact";
  component: "hero";
  _uid: string;
  [k: string]: any;
}

export interface HomepageStoryblok {
  hero: HomepageHeroStoryblok[];
  featuredStory?:
    | ISbStoryData<BlogPostStoryblok>
    | ISbStoryData<NewsArticleStoryblok>
    | ISbStoryData<PodcastStoryblok>
    | ISbStoryData<InDepthArticleStoryblok>
    | string;
  primaryActionBanner?: ActionBannerStoryblok[];
  links: RichtextStoryblok;
  linksAreTransparent?: boolean;
  promoBox1?: PromoBoxStoryblok[];
  spotlight?: SpotlightStoryblok[];
  promoBox2?: PromoBoxStoryblok[];
  metadata?: MetadataStoryblok[];
  component: "homepage";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface HomepageHeroStoryblok {
  title: string;
  description: string;
  images: MultiassetStoryblok;
  cta: ButtonLinkStoryblok[];
  component: "homepageHero";
  _uid: string;
  [k: string]: any;
}

export interface IframeStoryblok {
  source: string;
  component: "iframe";
  _uid: string;
  [k: string]: any;
}

export interface ImageOrVideoStoryblok {
  component: "imageOrVideo";
  _uid: string;
  [k: string]: any;
}

export interface InDepthArticleStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  image: AssetStoryblok;
  introText: string;
  date: string;
  component: "inDepthArticle";
  _uid: string;
  [k: string]: any;
}

export interface InfoPageStoryblok {
  header: (PageHeaderStoryblok | HeroStoryblok)[];
  isNavigationRoot?: boolean;
  metadata?: MetadataStoryblok[];
  content: RichtextStoryblok;
  component: "infoPage";
  _uid: string;
  [k: string]: any;
}

export interface ListItemStoryblok {
  ListItemText?: string;
  component: "ListItem";
  _uid: string;
  [k: string]: any;
}

export interface MarkdownStoryblok {
  content: string;
  component: "markdown";
  _uid: string;
  [k: string]: any;
}

export interface MetadataStoryblok {
  description?: string;
  creator?: string;
  component: "metadata";
  _uid: string;
  [k: string]: any;
}

export interface NestedRichTextStoryblok {
  richText: RichtextStoryblok;
  component: "nestedRichText";
  _uid: string;
  [k: string]: any;
}

export interface TableStoryblok {
  thead: {
    _uid: string;
    value?: string;
    component: number;
    [k: string]: any;
  }[];
  tbody: {
    _uid: string;
    body: {
      _uid?: string;
      value?: string;
      component?: number;
      [k: string]: any;
    }[];
    component: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}

export interface NestedTableStoryblok {
  title?: string;
  summary?: string;
  table?: TableStoryblok;
  component: "nestedTable";
  _uid: string;
  [k: string]: any;
}

export interface NewsArticleStoryblok {
  title: string;
  resources?: RelatedLinkStoryblok[];
  relatedNews?: RelatedNewsLinkStoryblok[];
  date: string;
  introText: string;
  content: RichtextStoryblok;
  image: AssetStoryblok;
  metadata?: MetadataStoryblok[];
  excludeFromHomepage?: boolean;
  component: "newsArticle";
  _uid: string;
  [k: string]: any;
}

export interface OrderedListStoryblok {
  StartingNumber?: string;
  ListItems?: ListItemStoryblok[];
  component: "OrderedList";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | AccordionStoryblok
    | AccordionGroupStoryblok
    | ActionBannerStoryblok
    | ActionBannerDefaultStoryblok
    | AuthorStoryblok
    | BlogPostStoryblok
    | ButtonLinkStoryblok
    | CardStoryblok
    | CardContentStoryblok
    | CardGridStoryblok
    | CategoryLandingPageStoryblok
    | CategoryNavigationStoryblok
    | GridStoryblok
    | GridItemStoryblok
    | GridSectionStoryblok
    | GridSectionItemStoryblok
    | HeroStoryblok
    | HomepageStoryblok
    | HomepageHeroStoryblok
    | IframeStoryblok
    | ImageOrVideoStoryblok
    | InDepthArticleStoryblok
    | InfoPageStoryblok
    | ListItemStoryblok
    | MarkdownStoryblok
    | MetadataStoryblok
    | NestedRichTextStoryblok
    | NestedTableStoryblok
    | NewsArticleStoryblok
    | OrderedListStoryblok
    | PageStoryblok
    | PageHeaderStoryblok
    | PodcastStoryblok
    | PromoBoxStoryblok
    | QuoteStoryblok
    | RelatedLinkStoryblok
    | RelatedNewsLinkStoryblok
    | SpotlightStoryblok
    | YoutubeEmbedStoryblok
  )[];
  metadata?: MetadataStoryblok[];
  wysiwyg?: RichtextStoryblok;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PageHeaderStoryblok {
  title: string;
  summary?: string;
  description?: string;
  cta?: ButtonLinkStoryblok[];
  ctaText?: string;
  ctaLink?: MultilinkStoryblok;
  component: "pageHeader";
  _uid: string;
  [k: string]: any;
}

export interface PodcastStoryblok {
  date: string;
  soundcloudEmbedID: string;
  introText: string;
  description: RichtextStoryblok;
  image?: AssetStoryblok;
  metadata?: MetadataStoryblok[];
  component: "podcast";
  _uid: string;
  [k: string]: any;
}

export interface PromoBoxStoryblok {
  heading: string;
  body?: RichtextStoryblok;
  cta?: ButtonLinkStoryblok[];
  useVideo?: boolean;
  image?: AssetStoryblok;
  youtubeEmbed?: YoutubeEmbedStoryblok[];
  swapMediaSide?: boolean;
  isTransparent?: boolean;
  component: "promoBox";
  _uid: string;
  [k: string]: any;
}

export interface QuoteStoryblok {
  quoteText: RichtextStoryblok;
  quoteAuthor: string;
  component: "quote";
  _uid: string;
  [k: string]: any;
}

export interface RelatedLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "relatedLink";
  _uid: string;
  [k: string]: any;
}

export interface RelatedNewsLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  publisher: string;
  date: string;
  component: "relatedNewsLink";
  _uid: string;
  [k: string]: any;
}

export interface SpotlightStoryblok {
  heading: string;
  mediaDescription?: string;
  stories: (
    | ISbStoryData<BlogPostStoryblok>
    | ISbStoryData<NewsArticleStoryblok>
    | ISbStoryData<InDepthArticleStoryblok>
    | ISbStoryData<PodcastStoryblok>
    | string
  )[];
  youtubeEmbed: YoutubeEmbedStoryblok[];
  isTransparent?: boolean;
  component: "spotlight";
  _uid: string;
  [k: string]: any;
}

export interface YoutubeEmbedStoryblok {
  title?: string;
  source: string;
  component: "youtubeEmbed";
  _uid: string;
  [k: string]: any;
}
