// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface AccordionStoryblok {
  title: string;
  displayTitleAsHeading?: boolean;
  headingLevel?: string;
  content: RichtextStoryblok;
  variant: "subtle" | "callout";
  component: "accordion";
  _uid: string;
  [k: string]: any;
}

export interface AccordionGroupStoryblok {
  accordions: AccordionStoryblok[];
  component: "accordionGroup";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface ActionBannerStoryblok {
  heading: string;
  body?: RichtextStoryblok;
  cta: ButtonLinkStoryblok[];
  image: AssetStoryblok;
  variant?: "fullWidth" | "fullWidthSubtle";
  component: "actionBanner";
  _uid: string;
  [k: string]: any;
}

export interface ActionBannerDefaultStoryblok {
  heading: string;
  body?: RichtextStoryblok;
  cta: ButtonLinkStoryblok[];
  variant?: "default" | "subtle";
  component: "actionBannerDefault";
  _uid: string;
  [k: string]: any;
}

export interface AuthorStoryblok {
  name: string;
  jobTitle?: string;
  image?: AssetStoryblok;
  component: "author";
  _uid: string;
  [k: string]: any;
}

export interface BlogPostStoryblok {
  title: string;
  image: AssetStoryblok;
  date: string;
  introText: string;
  content: RichtextStoryblok;
  author: (ISbStoryData<AuthorStoryblok> | string)[];
  metadata?: MetadataStoryblok[];
  component: "blogPost";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      id?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "story";
      target?: "_self" | "_blank";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      url?: string;
      cached_url?: string;
      anchor?: string;
      linktype?: "asset" | "url";
      target?: "_self" | "_blank";
      [k: string]: any;
    }
  | {
      email?: string;
      linktype?: "email";
      target?: "_self" | "_blank";
      [k: string]: any;
    };

export interface ButtonLinkStoryblok {
  text: string;
  link: MultilinkStoryblok;
  variant: "" | "cta" | "primary" | "secondary" | "inverse";
  component: "buttonLink";
  _uid: string;
  [k: string]: any;
}

export interface CalloutCardStoryblok {
  heading: string;
  headingLevel?: "" | "2" | "3" | "4" | "5" | "6";
  body: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "calloutCard";
  _uid: string;
  [k: string]: any;
}

export interface CalloutCardWithImageStoryblok {
  heading: string;
  headingLevel?: "" | "2" | "3" | "4" | "5" | "6";
  body: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  image: AssetStoryblok;
  component: "calloutCardWithImage";
  _uid: string;
  [k: string]: any;
}

export interface CardStoryblok {
  heading: string;
  headingLevel?: "" | "2" | "3" | "4" | "5" | "6";
  body: string;
  link?: MultilinkStoryblok;
  component: "card";
  _uid: string;
  [k: string]: any;
}

export interface CardGridStoryblok {
  cards: CardStoryblok[];
  component: "cardGrid";
  _uid: string;
  [k: string]: any;
}

export interface CardGridRowBasicStoryblok {
  columns?: "" | "2" | "3";
  gridItems: CardStoryblok[];
  component: "cardGridRowBasic";
  _uid: string;
  [k: string]: any;
}

export interface CardGridRowCalloutStoryblok {
  columns?: "" | "2" | "3";
  gridItems: CalloutCardStoryblok[];
  component: "cardGridRowCallout";
  _uid: string;
  [k: string]: any;
}

export interface CardGridRowCalloutWithImageStoryblok {
  columns?: "" | "2" | "3";
  gridItems: CalloutCardWithImageStoryblok[];
  component: "cardGridRowCalloutWithImage";
  _uid: string;
  [k: string]: any;
}

export interface CardGridRowTestimonialsStoryblok {
  columns: "" | "1" | "2" | "3";
  gridItems: TestimonialGridItemStoryblok[];
  component: "cardGridRowTestimonials";
  _uid: string;
  [k: string]: any;
}

export interface CardGridSectionStoryblok {
  heading?: string;
  headingLevel: string;
  leadText?: RichtextStoryblok;
  secondaryLeadText?: RichtextStoryblok;
  cards: (
    | CardGridRowBasicStoryblok
    | CardGridRowCalloutStoryblok
    | CardGridRowTestimonialsStoryblok
    | CardGridRowCalloutWithImageStoryblok
  )[];
  theme?: "" | "subtle" | "transparent";
  verticalPadding?: "" | "small" | "medium" | "large";
  component: "cardGridSection";
  _uid: string;
  [k: string]: any;
}

export interface CardListStoryblok {
  cards: CardListSectionItemStoryblok[];
  component: "cardList";
  _uid: string;
  [k: string]: any;
}

export interface CardListSectionStoryblok {
  heading?: string;
  headingLevel: string;
  leadText?: RichtextStoryblok;
  secondaryLeadText?: RichtextStoryblok;
  cards: CardListSectionItemStoryblok[];
  theme?: "" | "subtle" | "transparent";
  verticalPadding?: "" | "small" | "medium" | "large";
  component: "cardListSection";
  _uid: string;
  [k: string]: any;
}

export interface CardListSectionItemStoryblok {
  heading: string;
  headingLevel?: "" | "2" | "3" | "4" | "5" | "6";
  body: string;
  link: MultilinkStoryblok;
  component: "cardListSectionItem";
  _uid: string;
  [k: string]: any;
}

export interface CategoryLandingPageStoryblok {
  header?: (HeroStoryblok | PageHeaderStoryblok)[];
  metadata?: MetadataStoryblok[];
  content?: (
    | ActionBannerStoryblok
    | GridSectionStoryblok
    | ActionBannerDefaultStoryblok
    | PromoBoxStoryblok
    | CardListSectionStoryblok
    | TestimonialFullWidthStoryblok
    | CardGridSectionStoryblok
  )[];
  component: "categoryLandingPage";
  _uid: string;
  [k: string]: any;
}

export interface CategoryNavigationStoryblok {
  pageHeader: PageHeaderStoryblok[];
  cardGrid: CardGridStoryblok[];
  metadata?: MetadataStoryblok[];
  component: "categoryNavigation";
  _uid: string;
  [k: string]: any;
}

export interface FormEmbedStoryblok {
  title: string;
  formId: string;
  prefillId?: string;
  component: "formEmbed";
  _uid: string;
  [k: string]: any;
}

export interface FormPageStoryblok {
  header?: PageHeaderStoryblok[];
  metadata?: MetadataStoryblok[];
  content?: (NestedRichTextStoryblok | ButtonLinkStoryblok | FormEmbedStoryblok)[];
  panel?: NestedRichTextStoryblok[];
  component: "formPage";
  _uid: string;
  [k: string]: any;
}

export interface FullWidthSectionStoryblok {
  heading?: string;
  lead?: RichtextStoryblok;
  showHeading?: boolean;
  theme: "subtle" | "impact" | "transparent";
  content?: (ActionBannerStoryblok | CardGridStoryblok | PromoBoxStoryblok)[];
  component: "fullWidthSection";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | AccordionStoryblok
    | AccordionGroupStoryblok
    | ActionBannerStoryblok
    | ActionBannerDefaultStoryblok
    | AuthorStoryblok
    | BlogPostStoryblok
    | ButtonLinkStoryblok
    | CalloutCardStoryblok
    | CalloutCardWithImageStoryblok
    | CardStoryblok
    | CardGridStoryblok
    | CardGridRowBasicStoryblok
    | CardGridRowCalloutStoryblok
    | CardGridRowCalloutWithImageStoryblok
    | CardGridRowTestimonialsStoryblok
    | CardGridSectionStoryblok
    | CardListStoryblok
    | CardListSectionStoryblok
    | CardListSectionItemStoryblok
    | CategoryLandingPageStoryblok
    | CategoryNavigationStoryblok
    | FormEmbedStoryblok
    | FormPageStoryblok
    | FullWidthSectionStoryblok
    | GridStoryblok
    | GridItemStoryblok
    | GridSectionStoryblok
    | GridSectionItemStoryblok
    | HeroStoryblok
    | HomepageStoryblok
    | HomepageHeroStoryblok
    | IframeStoryblok
    | ImageEmbedStoryblok
    | ImageOrVideoStoryblok
    | ImageRichTextStoryblok
    | InDepthArticleStoryblok
    | InfogramEmbedStoryblok
    | InfoPageStoryblok
    | MarkdownStoryblok
    | MetadataStoryblok
    | NestedRichTextStoryblok
    | NestedTableStoryblok
    | NewsArticleStoryblok
    | OrderedListStoryblok
    | PageStoryblok
    | PageHeaderStoryblok
    | PanelStoryblok
    | PodcastStoryblok
    | PromoBoxStoryblok
    | QuoteStoryblok
    | RelatedLinkStoryblok
    | RelatedNewsLinkStoryblok
    | RichTextTableStoryblok
    | SpotlightStoryblok
    | TestimonialFullWidthStoryblok
    | TestimonialGridItemStoryblok
    | YoutubeEmbedStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface GridItemStoryblok {
  cols?: string;
  block?: CardStoryblok[];
  component: "gridItem";
  _uid: string;
  [k: string]: any;
}

export interface GridSectionStoryblok {
  heading?: string;
  lead?: RichtextStoryblok;
  showHeading?: boolean;
  theme: "subtle" | "impact" | "transparent";
  verticalPadding?: "small" | "medium" | "large";
  content?: GridSectionItemStoryblok[];
  component: "gridSection";
  _uid: string;
  [k: string]: any;
}

export interface GridSectionItemStoryblok {
  columns?: "12" | "6" | "4";
  cards?: CardStoryblok[];
  component: "gridSectionItem";
  _uid: string;
  [k: string]: any;
}

export interface HeroStoryblok {
  title: string;
  summary?: string;
  description?: string;
  image: AssetStoryblok;
  cta?: ButtonLinkStoryblok[];
  theme?: "subtle" | "impact";
  component: "hero";
  _uid: string;
  [k: string]: any;
}

export interface HomepageStoryblok {
  hero: HomepageHeroStoryblok[];
  featuredStory?:
    | ISbStoryData<BlogPostStoryblok>
    | ISbStoryData<NewsArticleStoryblok>
    | ISbStoryData<PodcastStoryblok>
    | ISbStoryData<InDepthArticleStoryblok>
    | string;
  primaryActionBanner?: ActionBannerStoryblok[];
  links: RichtextStoryblok;
  linksAreTransparent?: boolean;
  promoBox1?: PromoBoxStoryblok[];
  spotlight?: SpotlightStoryblok[];
  promoBox2?: PromoBoxStoryblok[];
  metadata?: MetadataStoryblok[];
  component: "homepage";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  [k: string]: any;
}[];

export interface HomepageHeroStoryblok {
  title: string;
  description: string;
  images: MultiassetStoryblok;
  cta: ButtonLinkStoryblok[];
  component: "homepageHero";
  _uid: string;
  [k: string]: any;
}

export interface IframeStoryblok {
  source: string;
  component: "iframe";
  _uid: string;
  [k: string]: any;
}

export interface ImageEmbedStoryblok {
  image: AssetStoryblok;
  component: "imageEmbed";
  _uid: string;
  [k: string]: any;
}

export interface ImageOrVideoStoryblok {
  component: "imageOrVideo";
  _uid: string;
  [k: string]: any;
}

export interface ImageRichTextStoryblok {
  imagePosition?: "" | "left" | "right";
  imageSize?: "small" | "medium" | "large";
  hideImagesOnSmallScreens?: "true" | "false";
  mainImage: AssetStoryblok;
  smallScreenImage?: AssetStoryblok;
  content: RichtextStoryblok;
  component: "imageRichText";
  _uid: string;
  [k: string]: any;
}

export interface InDepthArticleStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  image: AssetStoryblok;
  introText: string;
  date: string;
  component: "inDepthArticle";
  _uid: string;
  [k: string]: any;
}

export interface InfogramEmbedStoryblok {
  displayMode: "withRichText" | "standalone";
  infogramUrl: string;
  layoutVariant: "constrained" | "fullwidth";
  content: RichtextStoryblok;
  infogramPosition?: "left" | "right";
  infogramSize?: "medium" | "large";
  hideInfogramOnSmallScreens?: "true" | "false";
  component: "infogramEmbed";
  _uid: string;
  [k: string]: any;
}

export interface InfoPageStoryblok {
  header: (PageHeaderStoryblok | HeroStoryblok)[];
  metadata?: MetadataStoryblok[];
  hideSectionNav?: "true" | "false";
  hideInPageNav?: "true" | "false";
  content: RichtextStoryblok;
  component: "infoPage";
  _uid: string;
  [k: string]: any;
}

export interface MarkdownStoryblok {
  content: string;
  component: "markdown";
  _uid: string;
  [k: string]: any;
}

export interface MetadataStoryblok {
  description?: string;
  creator?: string;
  component: "metadata";
  _uid: string;
  [k: string]: any;
}

export interface NestedRichTextStoryblok {
  richText: RichtextStoryblok;
  component: "nestedRichText";
  _uid: string;
  [k: string]: any;
}

export interface TableStoryblok {
  thead: {
    _uid: string;
    value?: string;
    component: number;
    [k: string]: any;
  }[];
  tbody: {
    _uid: string;
    body: {
      _uid?: string;
      value?: string;
      component?: number;
      [k: string]: any;
    }[];
    component: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}

export interface NestedTableStoryblok {
  title?: string;
  summary?: string;
  table?: TableStoryblok;
  component: "nestedTable";
  _uid: string;
  [k: string]: any;
}

export interface NewsArticleStoryblok {
  title: string;
  resources?: RelatedLinkStoryblok[];
  relatedNews?: RelatedNewsLinkStoryblok[];
  date: string;
  introText: string;
  content: RichtextStoryblok;
  image: AssetStoryblok;
  metadata?: MetadataStoryblok[];
  component: "newsArticle";
  _uid: string;
  [k: string]: any;
}

export interface OrderedListStoryblok {
  startingNumber?: string;
  listType?: "" | "1" | "a" | "A" | "i" | "I";
  listItems: ListItemStoryblok[];
  component: "orderedList";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (
    | AccordionStoryblok
    | AccordionGroupStoryblok
    | ActionBannerStoryblok
    | ActionBannerDefaultStoryblok
    | AuthorStoryblok
    | BlogPostStoryblok
    | ButtonLinkStoryblok
    | CalloutCardStoryblok
    | CalloutCardWithImageStoryblok
    | CardStoryblok
    | CardGridStoryblok
    | CardGridRowBasicStoryblok
    | CardGridRowCalloutStoryblok
    | CardGridRowCalloutWithImageStoryblok
    | CardGridRowTestimonialsStoryblok
    | CardGridSectionStoryblok
    | CardListStoryblok
    | CardListSectionStoryblok
    | CardListSectionItemStoryblok
    | CategoryLandingPageStoryblok
    | CategoryNavigationStoryblok
    | FormEmbedStoryblok
    | FormPageStoryblok
    | FullWidthSectionStoryblok
    | GridStoryblok
    | GridItemStoryblok
    | GridSectionStoryblok
    | GridSectionItemStoryblok
    | HeroStoryblok
    | HomepageStoryblok
    | HomepageHeroStoryblok
    | IframeStoryblok
    | ImageEmbedStoryblok
    | ImageOrVideoStoryblok
    | ImageRichTextStoryblok
    | InDepthArticleStoryblok
    | InfogramEmbedStoryblok
    | InfoPageStoryblok
    | MarkdownStoryblok
    | MetadataStoryblok
    | NestedRichTextStoryblok
    | NestedTableStoryblok
    | NewsArticleStoryblok
    | OrderedListStoryblok
    | PageStoryblok
    | PageHeaderStoryblok
    | PanelStoryblok
    | PodcastStoryblok
    | PromoBoxStoryblok
    | QuoteStoryblok
    | RelatedLinkStoryblok
    | RelatedNewsLinkStoryblok
    | RichTextTableStoryblok
    | SpotlightStoryblok
    | TestimonialFullWidthStoryblok
    | TestimonialGridItemStoryblok
    | YoutubeEmbedStoryblok
  )[];
  metadata?: MetadataStoryblok[];
  wysiwyg?: RichtextStoryblok;
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PageHeaderStoryblok {
  title: string;
  summary?: string;
  description?: string;
  cta?: ButtonLinkStoryblok[];
  theme?: "subtle" | "impact";
  component: "pageHeader";
  _uid: string;
  [k: string]: any;
}

export interface PanelStoryblok {
  heading: string;
  headingLevel: string;
  content: RichtextStoryblok;
  variant?: "supporting" | "primary" | "impact";
  component: "panel";
  _uid: string;
  [k: string]: any;
}

export interface PodcastStoryblok {
  date: string;
  soundcloudEmbedID: string;
  introText: string;
  description: RichtextStoryblok;
  image?: AssetStoryblok;
  metadata?: MetadataStoryblok[];
  component: "podcast";
  _uid: string;
  [k: string]: any;
}

export interface PromoBoxStoryblok {
  heading: string;
  headingLevel: string;
  body?: RichtextStoryblok;
  cta?: ButtonLinkStoryblok[];
  media: (YoutubeEmbedStoryblok | ImageEmbedStoryblok)[];
  swapMediaSide?: boolean;
  imageAspectRatio?: "landscape" | "portrait";
  isTransparent?: boolean;
  verticalPadding?: "" | "small" | "medium" | "large";
  promotionalContent?: (ActionBannerDefaultStoryblok | CardGridRowTestimonialsStoryblok)[];
  component: "promoBox";
  _uid: string;
  [k: string]: any;
}

export interface QuoteStoryblok {
  quoteText: RichtextStoryblok;
  quoteAuthor: string;
  component: "quote";
  _uid: string;
  [k: string]: any;
}

export interface RelatedLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "relatedLink";
  _uid: string;
  [k: string]: any;
}

export interface RelatedNewsLinkStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  publisher: string;
  date: string;
  component: "relatedNewsLink";
  _uid: string;
  [k: string]: any;
}

export interface RichTextTableStoryblok {
  heading: string;
  headingLevel: "" | "2" | "3" | "4" | "5";
  summary?: RichtextStoryblok;
  hideSummaryText?: "" | "true" | "false";
  tableContent: RichtextStoryblok;
  component: "richTextTable";
  _uid: string;
  [k: string]: any;
}

export interface SpotlightStoryblok {
  heading: string;
  mediaDescription?: string;
  stories: (
    | ISbStoryData<BlogPostStoryblok>
    | ISbStoryData<NewsArticleStoryblok>
    | ISbStoryData<InDepthArticleStoryblok>
    | ISbStoryData<PodcastStoryblok>
    | string
  )[];
  youtubeEmbed: YoutubeEmbedStoryblok[];
  isTransparent?: boolean;
  component: "spotlight";
  _uid: string;
  [k: string]: any;
}

export interface TestimonialFullWidthStoryblok {
  quoteText: string;
  quoteName: string;
  quoteRole: string;
  image?: AssetStoryblok;
  link?: RelatedLinkStoryblok[];
  variant: "fullWidth" | "fullWidthWhite";
  component: "testimonialFullWidth";
  _uid: string;
  [k: string]: any;
}

export interface TestimonialGridItemStoryblok {
  quoteText: string;
  quoteName: string;
  quoteRole: string;
  image?: AssetStoryblok;
  variant: "default" | "transparent";
  component: "testimonialGridItem";
  _uid: string;
  [k: string]: any;
}

export interface YoutubeEmbedStoryblok {
  title?: string;
  source: string;
  component: "youtubeEmbed";
  _uid: string;
  [k: string]: any;
}
