import { Document } from "@nice-digital/search-client";

export const mockDocuments: Document[] = [
	{
		id: "1",
		tagsHigh: null,
		guidanceRef: null,
		xml: null,
		abstract: null,
		metaDescription: null,
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE Live Sitemap Crawl"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -1872403,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId: "https://www.nice.org.uk/pathways/test",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: ["NICE Pathway"],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery: "/pathways/test",
		publicationDate: "2021-04-06T12:00:00",
		lastUpdated: "2021-04-06T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: ["Test Resource Type"],
		guidanceStatus: [],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE Live Sitemap Crawl",
		sourceUrl: "https://www.nice.org.uk/pathways/test",
		staticAbstract: null,
		subSectionLinks: "",
		summaryUrl: null,
		tags: [],
		teaser: "Test teaser ",
		title: "Test title",
		titleNoHtml: null,
		boostValue: 75,
		score: 4.2157607,
		titleParts: ["Test title parts"],
		uKMISummaryUrl: "test",
		url: "https://www.nice.org.uk/pathways/test",
		debug: null,
	},
	{
		id: "2004268",
		tagsHigh: null,
		guidanceRef: null,
		xml: null,
		abstract: null,
		metaDescription:
			"Everything NICE has said on chronic kidney disease in children, young people and adults in an interactive flowchart.",
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE Live Pathways Crawl"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -2004268,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId: "https://pathways.nice.org.uk/pathways/chronic-kidney-disease",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: ["NICE Pathways"],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "NICE Pathway",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery: "/pathways/chronic-kidney-disease",
		publicationDate: "2011-05-10T12:00:00",
		lastUpdated: "2021-11-24T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: [],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE Live Pathways Crawl",
		sourceUrl: "https://pathways.nice.org.uk/pathways/chronic-kidney-disease",
		staticAbstract: null,
		subSectionLinks: "",
		summaryUrl: null,
		tags: [],
		teaser:
			"Everything NICE has said on chronic kidney disease in children, young people and adults in an interactive flowchart.",
		title: "Test pathway",
		titleNoHtml: null,
		boostValue: 150,
		score: 33.335373,
		titleParts: ["<b>Chronic kidney disease</b>"],
		uKMISummaryUrl: "test",
		url: "https://pathways.nice.org.uk/pathways/chronic-kidney-disease",
		debug: null,
	},
	{
		id: "1881210",
		tagsHigh: null,
		guidanceRef: null,
		xml: null,
		abstract: null,
		metaDescription: null,
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE Topic Pages"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -1881210,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId:
			"https://www.nice.org.uk/guidance/conditions-and-diseases/kidney-conditions/chronic-kidney-disease",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: [],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "Topic page",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery:
			"/guidance/conditions-and-diseases/kidney-conditions/chronic-kidney-disease",
		publicationDate: null,
		lastUpdated: null,
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: [],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE Topic Pages",
		sourceUrl:
			"https://www.nice.org.uk/guidance/conditions-and-diseases/kidney-conditions/chronic-kidney-disease",
		staticAbstract: null,
		subSectionLinks: "",
		summaryUrl: null,
		tags: [],
		teaser:
			"All NICE products on <mark>chronic kidney disease.</mark> Includes any guidance, advice, NICE Pathways and quality standards.",
		title: "<b>Chronic kidney disease</b>",
		titleNoHtml: null,
		boostValue: 250,
		score: 39.01663,
		titleParts: ["<b>Chronic kidney disease</b>"],
		uKMISummaryUrl: "test",
		url: "https://www.nice.org.uk/guidance/conditions-and-diseases/kidney-conditions/chronic-kidney-disease",
		debug: null,
	},
	{
		id: "2202814",
		tagsHigh: null,
		guidanceRef: "QS56",
		xml: null,
		abstract: null,
		metaDescription:
			"This quality standard covers early detection, diagnosis and management of metastatic spinal cord compression in adults (aged 18 and over) with cancer that has spread to the spine. It describes high-quality care in priority areas for improvement.",
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE QS chapters"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -2202814,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId: "https://www.nice.org.uk/guidance/qs56",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: ["Quality standards"],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "Quality standard",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery: "/guidance/qs56",
		publicationDate: "2014-02-27T12:00:00",
		lastUpdated: "2014-02-27T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: ["Published"],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE QS chapters",
		sourceUrl: "https://www.nice.org.uk/guidance/qs56",
		staticAbstract: null,
		subSectionLinks:
			'<SubSections>\r\n  <link url="/guidance/qs56">Overview</link>\r\n  <link url="/guidance/qs56/chapter/Introduction">Introduction</link>\r\n  <link url="/guidance/qs56/chapter/List-of-quality-statements">List of quality statements</link>\r\n  <link url="/guidance/qs56/chapter/Quality-statement-1-Information-about-recognising-the-symptoms-of-metastatic-spinal-cord-compression">Quality statement 1: Information about recognising the symptoms of metastatic spinal cord compression</link>\r\n  <link url="/guidance/qs56/chapter/Quality-statement-2-Imaging-and-treatment-plans-for-adults-with-suspected-spinal-metastases">Quality statement 2: Imaging and treatment plans for adults with suspected spinal metastases</link>\r\n  <link url="/guidance/qs56/chapter/Quality-statement-3-Imaging-and-treatment-plans-for-adults-with-suspected-metastatic-spinal-cord-compression">Quality statement 3: Imaging and treatment plans for adults with suspected metastatic spinal cord compression</link>\r\n  <link url="/guidance/qs56/chapter/Quality-statement-4-Coordinating-investigations-for-adults-with-suspected-metastatic-spinal-cord-compression">Quality statement 4: Coordinating investigations for adults with suspected metastatic spinal cord compression</link>\r\n  <link url="/guidance/qs56/chapter/Quality-statement-5-Coordinating-care-for-adults-with-metastatic-spinal-cord-compression">Quality statement 5: Coordinating care for adults with metastatic spinal cord compression</link>\r\n</SubSections>',
		summaryUrl: null,
		tags: [],
		teaser:
			"This quality standard covers early detection, diagnosis and management of metastatic spinal cord compression in adults (aged 18 and over) with cancer that has spread to the spine. It describes high-quality care in priority areas for improvement.",
		title: "Test quality standard",
		titleNoHtml: null,
		boostValue: 150,
		score: 55.266212,
		titleParts: ["Metastatic spinal cord compression in adults (<b>QS56</b>)"],
		uKMISummaryUrl: "test",
		url: "https://www.nice.org.uk/guidance/qs56",
		debug: null,
	},
	{
		id: "2202557",
		tagsHigh: null,
		guidanceRef: "NG45",
		xml: null,
		abstract: null,
		metaDescription:
			"This guideline covers routine preoperative tests for people aged over 16 who are having elective surgery. It aims to reduce unnecessary testing by advising which tests to offer people before minor, intermediate and major or complex surgery, taking into account specific comorbidities (cardiovascular, renal and respiratory conditions and diabetes and obesity). It does not cover pregnant women or people having cardiothoracic procedures or neurosurgery.",
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE NG chapters"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -2202557,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId: "https://www.nice.org.uk/guidance/ng45",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: ["Guidance"],
		niceGuidanceType: ["Clinical guidelines", "NICE guidelines"],
		niceAdviceType: [],
		niceResultType: "NICE guideline",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery: "/guidance/ng45",
		publicationDate: "2016-04-05T12:00:00",
		lastUpdated: "2016-04-05T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: ["Published"],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE NG chapters",
		sourceUrl: "https://www.nice.org.uk/guidance/ng45",
		staticAbstract: null,
		subSectionLinks:
			'<SubSections>\r\n  <link url="/guidance/ng45">Overview</link>\r\n  <link url="/guidance/ng45/chapter/Recommendations">Recommendations</link>\r\n  <link url="/guidance/ng45/chapter/Putting-this-guideline-into-practice">Putting this guideline into practice</link>\r\n  <link url="/guidance/ng45/chapter/Context">Context</link>\r\n  <link url="/guidance/ng45/chapter/Recommendations-for-research">Recommendations for research</link>\r\n  <link url="/guidance/ng45/chapter/Update-information">Update information</link>\r\n</SubSections>',
		summaryUrl: null,
		tags: [],
		teaser:
			"This guideline covers routine preoperative tests for people aged over 16 who are having elective surgery. It aims to reduce unnecessary testing by advising which tests to offer people before minor, intermediate and major or complex surgery, taking into account specific comorbidities (cardiovascular, renal and respiratory conditions and diabetes and obesity). It does not cover pregnant women or people having cardiothoracic procedures or neurosurgery.",
		title: "Routine preoperative tests for elective surgery (<b>NG45</b>)",
		titleNoHtml: null,
		boostValue: 165,
		score: 53.514725,
		titleParts: [
			"Routine preoperative tests for elective surgery (<b>NG45</b>)",
		],
		uKMISummaryUrl: "test",
		url: "https://www.nice.org.uk/guidance/ng45",
		debug: null,
	},
	{
		id: "2004486",
		tagsHigh: null,
		guidanceRef: null,
		xml: null,
		abstract: null,
		metaDescription:
			"Everything NICE has said on routine preoperative tests for people over 16 having elective surgery in an interactive flowchart",
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE Live Pathways Crawl"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -2004486,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId: "https://pathways.nice.org.uk/pathways/preoperative-tests",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: ["NICE Pathways"],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "NICE Pathway",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery: "/pathways/preoperative-tests",
		publicationDate: "2014-03-19T12:00:00",
		lastUpdated: "2020-08-19T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: [],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE Live Pathways Crawl",
		sourceUrl: "https://pathways.nice.org.uk/pathways/preoperative-tests",
		staticAbstract: null,
		subSectionLinks: "",
		summaryUrl: null,
		tags: [],
		teaser:
			"Everything NICE has said on routine preoperative tests for people over 16 having elective surgery in an interactive flowchart",
		title: "Preoperative tests",
		titleNoHtml: null,
		boostValue: 150,
		score: 20.13944,
		titleParts: ["Preoperative tests"],
		uKMISummaryUrl: "test",
		url: "https://pathways.nice.org.uk/pathways/preoperative-tests",
		debug: null,
	},
];

export const mockUncategorisedDocuments: Document[] = [
	{
		id: "2331480",
		tagsHigh: null,
		guidanceRef: null,
		xml: null,
		abstract: null,
		metaDescription:
			"Agenda and papers of the NICE public board meeting on 24 March 2021",
		accredited: false,
		alternativePublicationDate: null,
		altSourceNames: ["NICE Live Sitemap Crawl"],
		areaOfInterest: null,
		breadcrumbs: null,
		childDocumentCount: 0,
		childDocuments: [],
		childDocumentsUrl: null,
		clusterId: -2331480,
		evidenceTypes: [],
		impact: null,
		content: null,
		contentId:
			"https://www.nice.org.uk/get-involved/meetings-in-public/public-board-meetings/agenda-papers-march-2021",
		index: 0,
		lessSuitableForPrescribing: false,
		niceDocType: [],
		niceGuidanceType: [],
		niceAdviceType: [],
		niceResultType: "",
		parentPathTitle: null,
		parentPathUrl: null,
		parentPathWayUrl: null,
		pathAndQuery:
			"/get-involved/meetings-in-public/public-board-meetings/agenda-papers-march-2021",
		publicationDate: "1970-01-01T12:00:00",
		lastUpdated: "1970-01-01T12:00:00",
		expectedPublicationDate: null,
		consultationEndDate: null,
		consultationType: null,
		resourceType: [],
		guidanceStatus: [],
		publicationType: null,
		publisher: null,
		resourceCategory: null,
		relatedLinks: null,
		relatedLinkList: {},
		technologyType: null,
		topicSelectionDecision: null,
		sourceName: "NICE Live Sitemap Crawl",
		sourceUrl:
			"https://www.nice.org.uk/get-involved/meetings-in-public/public-board-meetings/agenda-papers-march-2021",
		staticAbstract: null,
		subSectionLinks: "",
		summaryUrl: null,
		tags: [],
		teaser:
			"Agenda and papers of the NICE public board meeting on 24 March 2021",
		title: "Test uncategorised",
		titleNoHtml: null,
		boostValue: 100,
		score: 10.671083,
		titleParts: ["papers", "board meeting agenda and papers: March 2021"],
		uKMISummaryUrl: "",
		url: "https://www.nice.org.uk/get-involved/meetings-in-public/public-board-meetings/agenda-papers-march-2021",
		debug: null,
	},
];
