version: '2.2'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210713
    container_name: nxt-selenium-hub
    ports:
      - '4444:4444'

  selenium-chrome:
    image: selenium/node-chrome:3.141.59-20210713
    container_name: nxt-selenium-chrome
    shm_size: '1gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  nxt-test-runner:
    build: .
    container_name: nxt-test-runner
    depends_on:
      - selenium-hub
      - next-web
    environment:
      - TEAMCITY_VERSION
    volumes:
      - ./:/next-web/tests
      - /next-web/tests/node_modules/
      - ./errorShots:/next-web/tests/errorShots

  # New Next Web (NextJS web app)
  next-web:
    image: nextweb:latest
    ## Uncomment the two lines below to run with a specific image with a specific Teamcity build number
    # image: xxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/nextweb:nnnn
    # command: ["npm", "run", "host-console-logging"]
    container_name: next-web
    build: ./../web
    depends_on:
      - mock-search-api
      - mock-publications
      - mock-indev
    ports:
      # Next Web runs on 8092 in PM2: see pm2.ecosystem.json in the web-host folder
      - '3000:3000'
    volumes:
      - ./../web:/web
    environment:
      - SEARCH_BASE_URL
      - PUBLICATIONS_BASE_URL
      - INDEV_BASE_URL
    networks:
      default:
        aliases:
          # Make sure the app uses a nice.org.uk domain so that the cookie banner license works
          - next-web-tests.nice.org.uk

  mock-search-api:
    build: https://github.com/nice-digital/mocks-apis.git#main:search-apis
    container_name: mock-search-api
    command: npm start
    networks:
      default:
        aliases:
          - mock-search-api.nice.org.uk

  mock-publications:
    build: https://github.com/nice-digital/mocks-apis.git#main:publications
    container_name: mock-publications
    command: npm start
    networks:
      default:
        aliases:
          - mock-publications.nice.org.uk

  mock-indev:
    build: https://github.com/nice-digital/mocks-apis.git#main:indev
    container_name: mock-indev
    command: npm start
    networks:
      default:
        aliases:
          - mock-indev.nice.org.uk
networks:
  default:
    name: next-web-functional-tests
