import { Inter, Lora } from "next/font/google";


import HeaderClient from "@/components/HeaderClient/HeaderClient";
import MainClient from "@/components/MainClient/MainClient";
import FooterClient from "@/components/FooterClient/FooterClient";
import { Container } from "@nice-digital/nds-container";
import { GoogleTagManager } from "@/components/GoogleTagManager/GoogleTagManager";
import G from "glob";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const inter = Inter({ subsets: ["latin"], variable: "--sans-font-family" });
const lora = Lora({ subsets: ["latin"], variable: "--serif-font-family" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

		{/* <head><title>TEST LAYOUT NESTED STATIC TITLE</title></head> */}
      	<body className={`${lora.variable} ${inter.variable}`}>

			<HeaderClient />
			<MainClient>
				<Container>
					{children}
				</Container>
			</MainClient>
			<FooterClient/>
			{/* <GoogleTagManager /> */}
		</body>
    </html>
  )
}
