import { Inter, Lora } from "next/font/google";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const inter = Inter({ subsets: ["latin"], variable: "--sans-font-family" });
const lora = Lora({ subsets: ["latin"], variable: "--serif-font-family" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
		<head><title>TEST LAYOUT NESTED STATIC TITLE</title></head>
      	<body className={`${lora.variable} ${inter.variable}`}>
			<header>
				<h1>HEADER - TEST LAYOUT</h1>
			</header>
			<div className="">{children}</div>
			<footer>FOOTER - TEST LAYOUT</footer>
		</body>
    </html>
  )
}
