public:
  search:
    # The base URL of the Single Search Endpoint (SSE) e.g. https://beta-search-api.nice.org.uk/api/
    baseURL: SEARCH_BASE_URL
  jotForm:
    baseURL: JOTFORM_BASE_URL
  storyblok:
    accessToken: STORYBLOK_TOKEN
server:
  feeds:
    publications:
      origin: PUBLICATIONS_BASE_URL
    inDev:
      origin: INDEV_BASE_URL
    jotForm:
      apiKey: JOTFORM_APIKEY
