# ! This is a PUBLIC repo so please don't put any sensitive info or secrets in here

# ! This file contains default config values for both 'public' config (accessible to both client and server-side code) and 'server' config (server-only runtime config).
# ! See https://edibleco.de/3jILey1 for NextJS runtime config docs

# Public config values are accessible to both client and server-side code:
public:
  # Name of the environment e.g. dev,test etc, used for logging to ELK
  environment: local
  # The base part of the URL where the website it hosted e.g https://dev.nice.org.uk
  baseUrl: http://localhost:3000
  # URL of the cookie banner script. It's config driven so we can point to the alpha CDN on non-live environments or even use localhost
  cookieBannerScriptUrl: https://cdn.nice.org.uk/cookie-banner/cookie-banner.min.js
  # The path to the public static assets once deployed: https://nextjs.org/docs/basic-features/static-file-serving.
  # Defaults to an empty string which means serving static files from the root. E.g. ./web/public/favicon.ico would be served from /favicon.ico
  publicBaseUrl: ''

# ! This is a PUBLIC repo so please don't put any sensitive info or secrets in here
# ! Use local.yml or local.json to override settings locally instead: https://edibleco.de/3dLJKiP
# ! Server config is accessible to server-only so is great for secrets (like API keys etc):
server:
