
# !!! This approach is deprecated! We should start switching to using environment variables
# !!! See the notice here: https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration

# ! This is a PUBLIC repo so please don't put any sensitive info or secrets in here

# ! This file contains default config values for both 'public' config (accessible to both client and server-side code) and 'server' config (server-only runtime config).
# ! See https://edibleco.de/3jILey1 for NextJS runtime config docs

# Public config values are accessible to both client and server-side code:
public:
  buildNumber: PLACEHOLDER
  # Name of the environment e.g. dev,test etc, used for logging to ELK
  environment: local
  # Name of the environment for auth purposes
  authEnvironment: "live"
  # The base part of the URL where the website it hosted e.g https://dev.nice.org.uk
  baseURL: http://localhost:4000
  # URL of the cookie banner script. It's config driven so we can point to the alpha CDN on non-live environments or even use localhost
  cookieBannerScriptURL: https://cdn.nice.org.uk/cookie-banner/cookie-banner.min.js
  # The path to the public static assets once deployed: https://nextjs.org/docs/basic-features/static-file-serving.
  # Defaults to an empty string which means serving static files from the root. E.g. ./web/public/favicon.ico would be served from /favicon.ico
  publicBaseURL: ''
  search:
    # The base URL of the Single Search Endpoint (SSE) e.g. https://beta-search-api.nice.org.uk/api/
    baseURL: http://localhost:19332/api
  cacheControl:
    # The default cache-control header used for 'dynamic' responses - apis/pages with getServerSideProps
    # See https://nextjs.org/docs/going-to-production#caching for more details on cache headers with NextJS
    # Note the use of s-max-age to cache in varnish, max-age to cache on the client and SWR for background refreshes
    defaultCacheHeader: public, s-max-age=300, max-age=480, stale-while-revalidate=1800
  jotForm:
    baseURL: https://nice.jotform.com
  storyblok:
    accessToken: SECRET
    ocelotEndpoint:
    enableRootCatchAll: false
  denyRobots: false

# ! This is a PUBLIC repo so please don't put any sensitive info or secrets in here
# ! Use local-development.yml or local-development.json to override settings locally instead: https://edibleco.de/3dLJKiP
# ! Server config is accessible to server-only so is great for secrets (like API keys etc):
server:
  cache:
    # Prefix added to all cache keys
    keyPrefix: next-web:local
    # The folder into which the feed cache is stored
    filePath: ./.cache/
    # The default TTL (time to live) (aka expiry duration), in seconds, for the object cache
    defaultTTL: 300
    # A longer TTL, in seconds, than the default, used for 'long-lived' cache entries that very rarely change.
    longTTL: 86400
    # Threshold for TTL, in seconds, below which object caches are refreshed in the background as per https://edibleco.de/3hyfpGG
    # Should be lower than defaultTTL.
    # Example: to check for fresh data every 5 minutes, it should be 300 seconds (5 * 60) lower than defaultTTL.
    refreshThreshold: 150
  feeds:
    publications:
      origin: SECRET
      apiKey: SECRET
    inDev:
      origin: SECRET
      apiKey: SECRET
    jotForm:
      # Notice how the JotForm base URL is public as it's used in iframes, unlike our internal services. But the API key is still secret as it's used server side
      apiKey: SECRET
